Add documentation for Vault plugins.
mesh-for-data/mesh-for-data pull request #591
Opened 2021-05-17 18:01 UTC by revit13

Vault Plugins are used to retrieved dataset credentials by the running modules as described in issue #406.
This PR adds documentation to the project website regarding Vault plugins.

2021-05-26 14:15 UTC, ronenkat requested changes
added review.
Please change the URLs to reflect the move to the mesh-for-data org.

2021-05-26 14:15 UTC, ronenkat commented on site/docs/concepts/vault_plugins.md
> +3. Have the [data catalog response](https://ibm.github.io/the-mesh-for-data/dev/reference/connectors/#connectors.CredentialsInfo) contain the Vault secret path which should be used to retrieve the cr
the URL is for the IBM org
can you add how to do it? 
change: have the ... contain --> Change the ... to contain
change: plugin could be  --> plugin is

2021-05-26 14:15 UTC, ronenkat commented on site/docs/concepts/vault_plugins.md
> +4. Have the [modules](./modules.md) use the [Vault related values](https://ibm.github.io/the-mesh-for-data/dev/reference/crds/#blueprintspecflowstepsindexargumentscopydestinationvault) to retrieve da
change: have --> update
URL to IBM org
can you explain/show example how?

2021-05-30 10:57 UTC, revit13 commented
@ronenkat Thanks for your review and comments. I created a new version to address them.

2021-06-08 06:45 UTC, revit13 commented
@ronenkat I applied additional changes based on your recent review. I appreciate it if you can review it again. Thanks

2021-06-08 07:51 UTC, ronenkat approved these changes
Thank you.

2021-06-08 19:25 UTC, merged