Change initialization of Vault client in the manager.
mesh-for-data/mesh-for-data pull request #609
Opened 2021-05-27 06:47 UTC by revit13

Current communication between the manager and Vault assumes a Vault token which is passed as an env var. This should be changed to the following:
1) get a Vault token from Vault using the manager role
2) continue communication with Vault using this Vault token
The manager role should be passed as env var after it was configured with the appropriate permissions for the manager.
This PR adds TODO and FIXME comments for future implementation of the functionally above.

2021-05-27 11:42 UTC, shlomitk1 commented on manager/controllers/utils/configuration.go
> +	VaultTTLKey      string = "VAULT_TTL"
We are not using neither VAULT_TOKEN nor VAULT_TTL, so why keep it?

2021-05-27 11:49 UTC, shlomitk1 commented on manager/controllers/utils/configuration.go
> +	VaultTTLKey      string = "VAULT_TTL"
Not sure what is the purpose of this PR. 
1. manager role env is not introduced, only mentioned in a comment
2. If vault token should be obtained by the manager, why is it still in the configmap and configuration.go file?

2021-05-30 11:48 UTC, revit13 commented
Following a private talk with @shlomitk1 I changed the pr to remove Vault connection from the manager code and updated the pr description accordently.

2021-05-30 12:00 UTC, shlomitk1 approved these changes

2021-05-30 12:04 UTC, shlomitk1 commented
@revit13 Please remove VAULT_TTL and VAULT_TOKEN from the chart values/ m4d-config as well.

2021-05-30 13:15 UTC, roee88 commented
@revit13 is there an issue for changing to make the manager setup policies dynamically?

2021-05-30 13:58 UTC, revit13 commented
@shlomitk1 Thanks will change that. @roee88 in issue  #585 the last task refers to that.

2021-05-30 18:09 UTC, revit13 commented
@shlomitk1 I left charts/m4d/templates/vault-credentials.yaml as it is still used...

2021-05-31 05:50 UTC, shlomitk1 commented
> 
> 
> @shlomitk1 I left charts/m4d/templates/vault-credentials.yaml as it is still used...

Secret should be left, but the reference to it in the manager deployment is no longer required.
https://github.com/mesh-for-data/mesh-for-data/blob/f06f70e3c6a3dcf643d7416a8578fba4f14a50ae/charts/m4d/templates/manager-deployment.yaml#L81-L84

2021-05-31 06:09 UTC, revit13 commented
> 
> 
> > @shlomitk1 I left charts/m4d/templates/vault-credentials.yaml as it is still used...
> 
> Secret should be left, but the reference to it in the manager deployment is no longer required.
> 
> https://github.com/mesh-for-data/mesh-for-data/blob/f06f70e3c6a3dcf643d7416a8578fba4f14a50ae/charts/m4d/templates/manager-deployment.yaml#L81-L84

Thanks @shlomitk1 Fixed.

2021-06-01 06:33 UTC, roee88 requested changes

2021-06-01 06:33 UTC, roee88 commented on pkg/vault/vault_interface_test.go
> +	t.Logf("Token = " + vaultToken)
No tokens in logs

2021-06-01 07:50 UTC, revit13 commented on pkg/vault/vault_interface_test.go
> +	t.Logf("Token = " + vaultToken)
Fixed Thanks

2021-06-01 07:53 UTC, roee88 approved these changes

2021-06-01 08:38 UTC, merged