Use new Vault helm chart in quickstart.
mesh-for-data/mesh-for-data pull request #665
Opened 2021-06-27 05:41 UTC by revit13

Signed-off-by: Revital Sur <eres@il.ibm.com>

2021-07-01 14:13 UTC, shlomitk1 commented on site/docs/get-started/quickstart.md
> +    helm dependency update m4d-charts/vault
charts/vault?

2021-07-01 14:14 UTC, shlomitk1 commented on site/docs/get-started/quickstart.md
> +    helm install vault m4d-charts/vault --create-namespace -n m4d-system \
charts instead of m4d-charts?

2021-07-01 14:20 UTC, shlomitk1 requested changes
m4d-charts does not exist.
Installation using charts/vault seems ok.

2021-07-01 16:16 UTC, roee88 commented
> m4d-charts does not exist.
> Installation using charts/vault seems ok.

I didn't follow the changes so it might be unrelated to your comments, but just in case: m4d-charts is our published charts. The vault chart will be published there in the next release. The instructions here update the dev version of the docs and as such only the "install latest development version from GitHub" must work. The rest must work once the next release is created.

2021-07-01 18:09 UTC, shlomitk1 commented
> 
> 
> > m4d-charts does not exist.
> > Installation using charts/vault seems ok.
> 
> I didn't follow the changes so it might be unrelated to your comments, but just in case: m4d-charts is our published charts. The vault chart will be published there in the next release. The instructions here update the dev version of the docs and as such only the "install latest development version from GitHub" must work. The rest must work once the next release is created.

Ah, ok, this explains why 'helm install vault m4d-charts/vault' did not work in my testing :-)

2021-07-01 18:09 UTC, shlomitk1 approved these changes

2021-07-05 15:04 UTC, shlomitk1 approved these changes

2021-07-05 17:01 UTC, merged